name: Demo Dev
concurrency: 
  group: demo-dev
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  start:
    runs-on: [self-hosted]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

  demo-ci-test:
    uses: ./.github/workflows/CI.yml
    needs: [start]

  finish:
    runs-on: [self-hosted]
    needs: [start, demo-ci-test]
    if: always()
    steps:
    - name: Write github summary
      run: |
        echo "# Build Dev Summary" >> $GITHUB_STEP_SUMMARY
