name: Demo Dev
concurrency: 
  group: demo-dev
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  start:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  demo-ci-test:
    uses: ./.github/workflows/CI.yml
    needs: [start]

  finish:
    runs-on: ubuntu-latest
    needs: [start, demo-ci-test]
    if: always()
    steps:
    - name: Write github summary
      run: |
        echo "# Build Dev Summary" >> $GITHUB_STEP_SUMMARY
