name: Demo Dev
concurrency: 
  group: demo-dev
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'release-**'
  
jobs:
  start:
   runs-on: ubuntu-latest
   outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
   steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT

  demo-ci-test:
    uses: ./.github/workflows/CI.yml
    needs: [start]

  finish:
    runs-on: ubuntu-latest
    needs: [start, demo-ci-test]
    if: always()
    steps:
    - name: Write github summary
      run: |
        echo "# Build Dev Summary" >> $GITHUB_STEP_SUMMARY
